# Generated by Django 3.1.2 on 2020-11-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_auto_20201102_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='EmployeeId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
